CREATE TABLE budget_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_budgetcategories PRIMARY KEY (id)
);

CREATE TABLE budgets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id  BIGINT,
    limit_amount DECIMAL                                 NOT NULL,
    user_id      BIGINT,
    CONSTRAINT pk_budgets PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    lastname VARCHAR(255),
    email    VARCHAR(255),
    version  INTEGER,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE pots
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    goal_amount    DECIMAL(10, 2)                          NOT NULL,
    current_amount DECIMAL(10, 2)                          NOT NULL,
    user_id        BIGINT,
    CONSTRAINT pk_pots PRIMARY KEY (id)
);

CREATE TABLE recurring_bills
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    amount          DECIMAL                                 NOT NULL,
    due_day         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid_this_month BOOLEAN                                 NOT NULL,
    user_id         BIGINT,
    CONSTRAINT pk_recurringbills PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    amount      DECIMAL                                 NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     BIGINT,
    budget_id   BIGINT,
    pot_id      BIGINT,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255),
    roles     VARCHAR(255),
    person_id BIGINT,
    version   INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE budgets
    ADD CONSTRAINT uc_budgets_categoryid UNIQUE (category_id);

ALTER TABLE budgets
    ADD CONSTRAINT uc_budgets_userid UNIQUE (user_id);

ALTER TABLE pots
    ADD CONSTRAINT uc_pots_userid UNIQUE (user_id);

ALTER TABLE recurring_bills
    ADD CONSTRAINT uc_recurringbills_userid UNIQUE (user_id);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_budgetid UNIQUE (budget_id);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_potid UNIQUE (pot_id);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_userid UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_personid UNIQUE (person_id);

ALTER TABLE budgets
    ADD CONSTRAINT FK_BUDGETS_ON_CATEGORYID FOREIGN KEY (category_id) REFERENCES budget_categories (id);

ALTER TABLE budgets
    ADD CONSTRAINT FK_BUDGETS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE pots
    ADD CONSTRAINT FK_POTS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE recurring_bills
    ADD CONSTRAINT FK_RECURRINGBILLS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_BUDGETID FOREIGN KEY (budget_id) REFERENCES budgets (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_POTID FOREIGN KEY (pot_id) REFERENCES pots (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PERSONID FOREIGN KEY (person_id) REFERENCES persons (id);