CREATE TABLE role_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roletypes PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    role_type_id BIGINT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    role_id BIGINT,
    CONSTRAINT pk_userroles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_ROLETYPEID FOREIGN KEY (role_type_id) REFERENCES role_types (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USERROLES_ON_ROLEID FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT FK_USERROLES_ON_USERID FOREIGN KEY (user_id) REFERENCES users (id);